(Almost) final version
quantling/create_vtl_corpus pull request #6
Opened 2024-12-08 19:25 UTC by JoJoBarthold2

This fixes the last  big problems with the code
Counting total words should now work
More comments
Check corpus now works the same for every situation
Word Types are now counted
Code was linted ( except some parts that @derNarr wrote)
Documentation was improved

2024-12-09 10:36 UTC, derNarr requested changes
Please change some of the small things I commented.

2024-12-09 10:36 UTC, derNarr commented on .gitignore
> +# Byte-compiled / optimized / DLL files
From here onward it looks like a pretty exhaustive list. Do we really need to gitignore all these? I am rather favoring a "minimal" gitignore than an exhaustive one.

2024-12-09 10:36 UTC, derNarr commented on README.rst
> +.. code:: bash
empty line missing before ``..code:: bash``?

2024-12-09 10:36 UTC, derNarr commented on .zenodo.json
This file needs to be removed. IMHO

2024-12-09 10:36 UTC, derNarr commented on docs/requirements.txt
> +numpy==1.26.4
Do we still need to pin numpy to 1.26.4? I would rather have no pinned versions in here.

2024-12-09 10:36 UTC, derNarr commented on docs/source/glossary.rst
Remove empty lines below "underlines of headings".

2024-12-09 10:36 UTC, derNarr commented on docs/source/issues.rst
> +
remove empty line

2024-12-09 10:36 UTC, derNarr commented on docs/tests/test_mfa_to_sampa_dict.py
> +    This test checks if the mfa_to_sampa_dict is working and produces a phoneme. It does not check if the phoneme is acutally accepted by VTL
break into two lines

2024-12-09 10:36 UTC, derNarr commented on docs/tests/test_mfa_to_sampa_dict.py
> +    This test checks if each phoneme in the mfa_to_sampa_dict is actually a phoneme and not just silent noise since VTL will not give an error if the phoneme is not a phoneme
Break into two lines

2024-12-09 10:36 UTC, derNarr commented on poetry.lock
Do we need this file in the repo?

2024-12-17 19:05 UTC, JoJoBarthold2 commented on poetry.lock
no

2024-12-17 19:58 UTC, merged